#
# CORE
# Copyright (c)2010-2012 the Boeing Company.
# See the LICENSE file included in this distribution.
#
''' Sample user-defined service.
'''
import os

from core.service import CoreService, addservice
from core.misc.ipaddr import IPv4Prefix, IPv6Prefix

class AdsbIn(CoreService):
    ''' This is a sample user-defined service.
    '''
    # a unique name is required, without spaces
    _name = "AdsbIn"
    # you can create your own group here
    _group = "Aviation"
    # list of other services this service depends on
    _depends = ()
    # per-node directories
    _dirs = ()
    # generated files (without a full path this file goes in the node's dir,
    #  e.g. /tmp/pycore.12345/n1.conf/)
    _configs = ('adsb_in.cfg', 'adsbin.sh')
    # this controls the starting order vs other enabled services
    _startindex = 50
    # list of startup commands, also may be generated during startup
    _startup = ('sh adsbin.sh',)
    # list of shutdown commands
    _shutdown = ()

    @classmethod
    def generateconfig(cls, node, filename, services):
        ''' Return a string that will be written to filename, or sent to the
            GUI for user customization.
        '''
        if filename == "adsbin.sh":
            # return an (x, y,z) tuple representing this object's position
            cfg = "#!/bin/sh\n"
            cfg += "# auto-generated by AdsbIn (adsbin.py)\n"
            cfg += "sleep 15\n"
            cfg += "echo Lat/Lng/Alt: {}\n".format(node.session.location.getgeo(node.position.x, node.position.y, node.position.z))
            cfg += "python -m atn.surveillance.adsb.adsb_in {} {} {}\n".format(node.position.x, node.position.y, node.position.z)

        elif filename == "adsb_in.cfg":
            cfg = "[General]\n"
            cfg += "id = %s\n" % node.objid
            cfg += "destinations = dump1090\n\n"
            cfg += "[dump1090]\n"
            cfg += "type = dump1090\n"
            cfg += "server = localhost\n"
            cfg += "port = 30001\n\n"
            cfg += "[mlat]\n"
            cfg += "type = client\n"
            cfg += "addr = 172.17.255.254\n"
            cfg += "port = 12270\n\n"

        return cfg

    @staticmethod
    def subnetentry(x):
        ''' Generate a subnet declaration block given an IPv4 prefix string
            for inclusion in the config file.
        '''
        if x.find(":") >= 0:
            # this is an IPv6 address
            return ""
        else:
            net = IPv4Prefix(x)
            return 'echo "  network %s"' % (net)

# this line is required to add the above class to the list of available services
addservice(AdsbIn)
